import os, json, requests
import boto3
import psycopg

# --- Config ---
AURORA_DSQL_CLUSTER_ID = os.environ["AURORA_DSQL_CLUSTER_ID"]     # e.g. yntgpodopbhatcokbhmzevgtxe
DB_NAME = os.environ.get("DB_NAME", "postgres")
DB_USER = os.environ.get("DB_USER", "admin")
REGION  = os.environ.get("AWS_REGION", "us-east-1")

# --- DSQL client ---
dsql = boto3.client("dsql", region_name=REGION)

# 1) Discover endpoint
cluster = dsql.get_cluster(identifier=AURORA_DSQL_CLUSTER_ID)["cluster"]
HOST = cluster["endpoint"]["hostname"]     # e.g. <cluster>.dsql.us-east-1.on.aws
PORT = cluster["endpoint"]["port"]         # typically 5432

# 2) Generate short-lived IAM auth token
token = dsql.generate_db_connect_auth_token(
    identifier=AURORA_DSQL_CLUSTER_ID,
    database=DB_NAME,
    dbUser=DB_USER,
)["authToken"]

# 3) Connect over PostgreSQL wire protocol (TLS required)
conn_str = (
    f"host={HOST} port={PORT} dbname={DB_NAME} user={DB_USER} "
    f"password={token} sslmode=require"
)

with psycopg.connect(conn_str) as conn, conn.cursor() as cur:
    cur.execute("""
        CREATE TABLE IF NOT EXISTS api_events (
            id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ext_id      text NOT NULL,
            payload     jsonb NOT NULL,
            created_at  timestamptz DEFAULT now()
        )
    """)

    # Placeholder API call; replace with your real endpoint.
    resp = requests.get("https://api.example.com/events?limit=5", timeout=10)
    resp.raise_for_status()
    events = resp.json()

    rows = [(str(e["id"]), json.dumps(e)) for e in events]
    cur.executemany("INSERT INTO api_events (ext_id, payload) VALUES (%s, %s)", rows)

    cur.execute("""
        SELECT ext_id, payload->>'type' AS type
        FROM api_events
        ORDER BY created_at DESC
        LIMIT 5
    """)
    for ext_id, ev_type in cur.fetchall():
        print(ext_id, ev_type)
